name: Build and Deploy HTML

on:
  push:
    branches:
      - main  # mainブランチに変更が加わると実行
  pull_request:
    branches:
      - main  # mainブランチへのプルリクエストが作成されたときにも実行
  repository_dispatch:
    types: [trigger-from-discord]

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu環境で実行
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # リポジトリのコードをチェックアウト

      - name: Set up Python
        uses: actions/setup-python@v2  # Python環境をセットアップ
        with:
          python-version: '3.x'  # 使用するPythonのバージョン

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Japanese Fonts
        run: sudo apt-get update && sudo apt-get install -y fonts-ipaexfont

      - name: Run the script
        run: |
          python main.py

      - name: Commit generated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Generated HTML"
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/shunnsoku7187/hok.git
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload files to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.2
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: list_html/
          server-dir: /public_html/